runtime: nodejs20
entrypoint: node index.js
env: standard

env_variables:
  MONGODB_URI: "mongodb+srv://alperendonmez:FDtiyWc5ZHphArdF@alperen-dev.yhsnjpo.mongodb.net/?retryWrites=true&w=majority&authSource=admin"
  PORT: 2000
