name: mobilektam
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#D7E9F1"
  #branding: assets/brandingbig.png
  #branding_bottom_padding: 24

  android_12:
    image: assets\ektamcon.jpg
    #branding: assets/brandingbig.png
    #branding_bottom_padding: 24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ektamlogo.jpg
    - assets/ektamcon.jpg
    - assets/branding.png
    - assets/brandingbig.png